# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Is every constructor written after the file that declares its type? Run with the other hygiene
# checks:
#
#     julia --project -e 'using Pkg; Pkg.test(; test_args = ["extras_clean.jl"])'
#
# The audit itself is `data/src/constructororder.jl`, which also runs standalone for the report.
module TestCleanConstructorOrder

using EcoSISTEM
using Test

include(joinpath(pkgdir(EcoSISTEM), "data", "src", "constructororder.jl"))
using .ConstructorOrderAudit

@testset "Constructor order" begin
    report = constructororder_report()

    # **The invariant.** A constructor written in a file included before its type's own file is
    # discarded silently - Julia makes a fresh generic function for the not-yet-declared name, and
    # the later `struct` replaces the binding without a word. Nothing else in the suite can see it:
    # the package loads, and only a call to that constructor fails.
    @test isempty(report.violations)

    # **Not vacuous**, which had to be established rather than assumed. The audit originally matched
    # only 8 types and 1 constructor, because the declaration pass did not unwrap the `doc` node a
    # docstring puts around a definition - so every documented type, which is nearly all of them,
    # was invisible and every constructor of one was skipped as "not ours". These bounds are what
    # would catch that regression. They are lower bounds, so adding a type does not fail them.
    @test report.ntypes >= 150
    @test report.nconstructors >= 20
    @test report.nfiles >= 50

    # **What this does NOT catch, measured 2026-09-04.** The audit reads source text, so it sees
    # every literal declaration - 197 of the 197 `struct`/`abstract type` lines in `src/*.jl`, and
    # the submodule directories contain none. What it cannot see is a type generated by a macro:
    # there are 53 `@nicheaxis` calls, and each declares a type that no parser can find without
    # expanding the macro. So a constructor for an *axis* type is unchecked here.
    # ⭐ Those are covered from the other side by `clean_TypeOrder.jl` and `clean_Architecture.jl`,
    # which work from the loaded module and so see macro-generated types.
end

end
