# Ignore ClimatePref for now - not possible to test
# as relies on access to v large datasets.
ignore:
  - "src/ClimatePref"
coverage:
  status:
     project:
       default:
         threshold: 0.2%
