comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "dev"
coverage:
  status:
     project:
       default:
         threshold: 0.2%
ignore:
  - "src/Epidemiology/data_utils.jl"
# We can't pull pipeline data through travis currently.
# Issues with boydorr.ac.uk ftp server.
