[params]
  burnin = 109 
  interval = 0.08333333333
  times = 109 
  timestep = 0.08333333333
  unit = "year"
[measure]
  measures = "norm_sub_alpha"
meta_measures = false 
  qs = [1.0]
[datadump]
  interval = 1
  outfile = "/home/claireh/Documents/TOML/NH_sw_tp_200/data/"
