[params]
  burnin = 1 
  interval = 0.08333333333
  times = 218 
  timestep = 0.08333333333
  unit = "year"
[measure]
  measures = "NormalisedBeta"
meta_measures = true 
  qs = [1.0]
[datadump]
  interval = 1
  outfile = "/home/claireh/Documents/TOML/NH_sw_tp_500/data/all/"
