dir = "/Users/claireh/Documents/PhD/GIT/ClimatePref/data/"
[grid]
gridsize = [534, 242]
resolution = 0.375
unit = "deg"
maxX = 180.0
minX = -20.0
maxY = 90.0
minY = 0.0
[traits]
  [traits.temperature]
  file = "Temperature.jld"
  name = "Temperature"
  type = "TempBin"
  [traits.rainfall]
  file = "Rainfall.jld"
  name = "Rainfall"
  type = "RainBin"

[climate]
  [climate.temperature]
  file = "CERA"
  search = "cera_20C"
  name = "t2m"
  type = "CERA-20C"

  [climate.rainfall]
  file = "wc"
  name = "wc2.0_5m_prec"
  type = "Worldclim"
  upscale = 2

 [budget]
  [budget.solar]
  file = "wc"
  name = "wc2.0_5m_srad"
  type = "Worldclim"
  upscale = 2

  [budget.water]
  fromclimate = true

[species]
  names = ["Trifolium repens", "Urtica dioica", "Achillea millefolium"]
  allnative = true

  [species.params]
  birth = 0.6
  death = 0.6
  long = 1.0
  surv = 0.5
  boost = 1000.0
  grid = [533, 239]
  individuals = 100
  unit = "month"

[requirements]
  allsame = true

  [requirements.solar]
  req = 2
  unit = "day^-1kJm^-2"
  [requirements.water]
  req = 0.5
  unit = "mm"

[movement]
  type = "GaussianKernel"
  distance = 10.0
  threshold = 10e-4
  unit = "km"

[active]
  file = "World_new.tif"
  upscale = 2
[locs]
  file = "GBIF_3spp"

[relationship]
  multiplicative = true
  [relationship.temperature]
  type = "Trapeze"
  [relationship.rainfall]
  type = "Uniform"
