[params]
  burnin = 1
  interval = 0.08333333333
  times = 10
  timestep = 0.08333333333
  unit = "year"
[measure]
  measures = "norm_sub_alpha"
  qs = [1.0]
[datadump]
  interval = 1
  outfile = "examples/TOML/NH_sw_tp_3/data/"
