name: JuliaNightly
# Nightly Scheduled Julia Nightly Run

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly at 2 AM UTC Sunday
  workflow_dispatch:

jobs:
  test:
    name: Julia Nightly - Ubuntu - x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up julia
        uses: julia-actions/setup-julia@v2
        with:
          version: nightly
          arch: x64
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
        with:
          ignore-no-cache: true
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
