name: JuliaNightly
# Nightly Scheduled Julia Nightly Run
on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * 0'  # Weekly at 2 AM UTC Sunday
  pull_request:

jobs:
  test:
    name: Julia Nightly - Ubuntu - x64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up julia
        uses: julia-actions/setup-julia@v1
        with:
          version: nightly
          arch: x64
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia-actions/julia-runtest@latest
