name: Simulation testing

# run workflow on push
on:
  push:
    branches: actions
  pull_request:

jobs:
  dru-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [‘1.4’, ‘1.5’, nightly]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up julia
      uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
    - name: Build package
      uses: julia-actions/julia-buildpkg@master
      uses: julia-actions/julia-runtest@master
    - name: Run tests
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
      run: julia --project=test/ test/runtests.jl
