name: CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  pull_request:

permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
  actions: write
  contents: read

jobs:
  EcoSISTEM-tests:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        julia-version:
          - '1.9'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        R-version:
          - 'release'
        arch:
          - x64
          - arm64
        experimental:
          - false
        exclude:
          - os: macOS-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: arm64
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.arch }}
    - name: Cache
      uses: julia-actions/cache@v2
    - name: Build package
      uses: julia-actions/julia-buildpkg@v1
    - name: Running
      uses: julia-actions/julia-runtest@v1
    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
